# For testing of production
version: '3.8'

services:
  app:
    image: ruslan0688/laravel-app-devops
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["sh", "-c", "php artisan migrate:fresh && php artisan test"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_KEY=base64:G7sNR0M8Cyew7OX/K0Pl7WUHdxTx8nWPuPkDfQhIk3k=
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - app/.env.testing

  db:
    image: postgres:latest
    ports:
      - "0.0.0.0:5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=ruslan
      - POSTGRES_PASSWORD=RG2023!
      - POSTGRES_DB=ruslan  # This should match the database name you want
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ruslan"]
      interval: 5s
      timeout: 5s
      retries: 5
