FROM php:8.2-apache
WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    libpq-dev \
    libonig-dev \
    libzip-dev \
    postgresql-client \
    && docker-php-ext-install pdo pdo_pgsql pdo_mysql

# Важно для кеширования слоев   
COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

COPY app/. .

EXPOSE 8080

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8080"]
