# For testing of production
version: '3.8'

services:
  app:
    image: ruslan0688/laravel-app-devops
    build:
      context: .
      dockerfile: Dockerfile.production
    #command: ["php", "artisan", "test"]
    command: ["php", "app/vendor/bin/phpunit"]
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DATABASE_NAME=${DB_DATABASE}
      - DATABASE_USERNAME=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD} 
    env_file:
      - app/.env
