- hosts: all
  become: yes
  tags: deploy
  vars:
    rollback_batch: "{{ rollback_batch | default(1) }}"

  tasks:
    - name: Roll back DB migration
      community.docker.docker_container_exec:
        container: laravel-app
        command: "php artisan migrate:rollback --batch={{ rollback_batch }}"   
