name: push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Fetch all tags
      - name: Fetch all tags
        run: git fetch --tags

      # Get the latest tag
      - name: Get the latest tag
        id: get_tag
        run: echo "TAG=$(git tag --sort=-creatordate | head -n 1)" >> $GITHUB_ENV

      # Output the latest tag
      - name: Output latest tag
        run: echo "The latest tag is: $TAG"
   
