name: Print Commit Message

on:
  push:
    branches:
      - main

jobs:
  print-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest commit message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Latest commit message: $COMMIT_MESSAGE"
      
      - name: Get tag
        run: |
          MESSAGE=$(git tag -1 --pretty=%B)
          echo "Latest tag: $MESSAGE"

