name: push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure that all tags are fetched for getting the latest tag

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get latest tag
        id: get_tag
        run: echo "LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Set up environment variables
        run: |
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> app/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> app/.env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> app/.env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> app/.env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> app/.env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> app/.env

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build App
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: |
            ruslan0688/laravel-app-devops:latest
            ruslan0688/laravel-app-devops:${{ env.LATEST_TAG }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Check Docker Compose version
        run: docker-compose --version

      - name: Run Tests
        run: make ci

