name: push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'Ruslan'
          git config --global user.email 'r.gusseinov@mail.ru'

      - name: Get the ref type
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_REF_TYPE

      - name: Output the tag
        run: echo "The latest tag is ${{ env.tag }}"

