name: Push

on:
  push:
    branches:
      - main

jobs:
  create-and-push-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get current version
        id: get_version
        run: echo "CURRENT_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          VERSION=${{ env.CURRENT_VERSION }}
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag -a ${{ env.NEW_VERSION }} -m "Automated tag creation"
          git push origin ${{ env.NEW_VERSION }}

      - name: Output new tag
        run: echo "The new tag is ${{ env.NEW_VERSION }}"

